apiVersion: v1
kind: Service
metadata:
  labels:
    app: cluster-status
    app.kubernetes.io/component: webserver
    app.kubernetes.io/managed-by: nimitz
    app.kubernetes.io/name: cluster-status
    app.kubernetes.io/part-of: cluster-status
    app.kubernetes.io/version: 3.6.1
  name: cluster-status
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cluster-status
  type: ClusterIP
